concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
          ref: main
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: JoshuaKGoldberg/release-it-action@160bc18e6032d4a7653df46c4eb6a148a0b6d961 # v0.3.0

name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
